<?php
header('Content-Type: text/html; charset=utf-8');
require_once('security.php');

// Initialize session if not started
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}

// Language handling
if (isset($_GET['lang'])) {
    $_SESSION['lang'] = $_GET['lang'];
} elseif (!isset($_SESSION['lang'])) {
    $_SESSION['lang'] = 'en'; // Default to English
}

$lang = $_SESSION['lang'];

// Language strings
$translations = [
    'en' => [
        'title' => 'Student List',
        'list_title' => 'Registered Students',
        'print_title' => 'Student List Report',
        'school_name' => 'Al-Madrasa Al-Farooqiyah Li Tajweed Wal Qira\'at',
        'school_address' => 'New Colony Matta Swat, Pakistan',
        'no_records' => 'No students found.',
        'sr_no' => '#',
        'father_name_label' => 'Father Name:',
        'mobile_label' => 'Mobile:',
        'reg_no_label' => 'Registration Number:',
        'guardian_mobile_label' => 'Guardian Mobile:',
        'guardian_cnic_label' => 'Guardian CNIC:',
        'class_or_course' => 'Class/Course:',
        'session_label' => 'Session:',
        'filter_by_class' => 'Filter by Class',
        'filter_by_village' => 'Filter by Village Council',
        'filter_by_status' => 'Filter by Status',
        'all_classes' => 'All Classes',
        'all_villages' => 'All Village Councils',
        'all_status' => 'All Students',
        'status_active' => 'Active',
        'status_leave' => 'Leave',
        'status_struck_off' => 'Struck Off',
        'status' => 'Status',
        'print_date' => 'Print Date',
        'total_students' => 'Total Students',
        'generated_by' => 'Generated by',
        'village_council' => 'Village Council',
        'student_information' => 'Student Information',
        'guardian_information' => 'Guardian Information',
        'class_session' => 'Class/Session',
        'report_id' => 'Report ID',
        'filter_criteria' => 'Filter Criteria',
        'search' => 'Search',
        'class' => 'Class',
        'village' => 'Village',
        'status_filter' => 'Status',
        'print' => 'Print',
        'save_pdf' => 'Save PDF',
        'close' => 'Close'
    ],
    'ur' => [
        'title' => 'طلبہ کی فہرست',
        'list_title' => 'رجسٹرڈ طلبہ',
        'print_title' => 'طلبہ کی فہرست کی رپورٹ',
        'school_name' => 'المدرسہ الفاروقیہ للتجوید والقراءت',
        'school_address' => 'نیو کالونی مٹہ سوات، پاکستان',
        'no_records' => 'کوئی طالب علم نہیں ملا',
        'sr_no' => 'نمبر',
        'father_name_label' => 'والد کا نام:',
        'mobile_label' => 'موبائل نمبر:',
        'reg_no_label' => 'رجسٹریشن نمبر:',
        'guardian_mobile_label' => 'سرپرست کا موبائل:',
        'guardian_cnic_label' => 'سرپرست کا شناختی کارڈ:',
        'class_or_course' => 'کلاس/کورس:',
        'session_label' => 'سیشن:',
        'filter_by_class' => 'کلاس کے مطابق فلٹر کریں',
        'filter_by_village' => 'ویلیج کونسل کے مطابق فلٹر کریں',
        'filter_by_status' => 'اسٹیٹس کے مطابق فلٹر کریں',
        'all_classes' => 'تمام کلاسیں',
        'all_villages' => 'تمام ویلیج کونسلیں',
        'all_status' => 'تمام طلبہ',
        'status_active' => 'فعال',
        'status_leave' => 'چھٹی پر',
        'status_struck_off' => 'خارج شدہ',
        'status' => 'اسٹیٹس',
        'print_date' => 'پرنٹ کی تاریخ',
        'total_students' => 'کل طلبہ',
        'generated_by' => 'تیار کردہ',
        'village_council' => 'ویلیج کونسل',
        'student_information' => 'طالب علم کی معلومات',
        'guardian_information' => 'سرپرست کی معلومات',
        'class_session' => 'کلاس/سیشن',
        'report_id' => 'رپورٹ شناختی نمبر',
        'filter_criteria' => 'فلٹر کے معیارات',
        'search' => 'تلاش',
        'class' => 'کلاس',
        'village' => 'ویلیج',
        'status_filter' => 'اسٹیٹس',
        'print' => 'پرنٹ کریں',
        'save_pdf' => 'PDF محفوظ کریں',
        'close' => 'بند کریں'
    ]
];

require_once('conn_inc.php');

// Get filter parameters
$search = isset($_GET['search']) ? mysqli_real_escape_string($conn, $_GET['search']) : '';
$class_filter = isset($_GET['class_filter']) ? intval($_GET['class_filter']) : 0;
$village_filter = isset($_GET['village_filter']) ? intval($_GET['village_filter']) : 0;
$status_filter = isset($_GET['status_filter']) ? $_GET['status_filter'] : '0';

// Build WHERE clause
$where_conditions = [];

if (!empty($search)) {
    $where_conditions[] = "(
        sr.name LIKE '%$search%' OR 
        sr.father_name LIKE '%$search%' OR 
        sr.mobile LIKE '%$search%' OR 
        sr.reg_no LIKE '%$search%' OR 
        sr.guardian_name LIKE '%$search%' OR 
        sr.guardian_mobile LIKE '%$search%' OR 
        sr.guardian_cnic LIKE '%$search%' OR
        sr.id LIKE '%$search%'
    )";
}

if ($class_filter > 0) {
    $where_conditions[] = "sc.class_id = '$class_filter'";
}

if ($village_filter > 0) {
    $where_conditions[] = "sr.village_council_id = '$village_filter'";
}

if ($status_filter !== 'all') {
    $where_conditions[] = "sr.status = '$status_filter'";
}

$where_clause = '';
if (!empty($where_conditions)) {
    $where_clause = 'WHERE ' . implode(' AND ', $where_conditions);
}

// Get filter labels for display
$class_name = '';
if ($class_filter > 0) {
    $class_result = $conn->query("SELECT title FROM classes WHERE id = $class_filter");
    if ($class_result && $class_result->num_rows > 0) {
        $class_row = $class_result->fetch_assoc();
        $class_name = $class_row['title'];
    }
}

$village_name = '';
if ($village_filter > 0) {
    $village_result = $conn->query("SELECT title FROM village_councils WHERE id = $village_filter");
    if ($village_result && $village_result->num_rows > 0) {
        $village_row = $village_result->fetch_assoc();
        $village_name = $village_row['title'];
    }
}

$status_text = '';
if ($status_filter == '0') $status_text = $translations[$lang]['status_active'];
elseif ($status_filter == '1') $status_text = $translations[$lang]['status_leave'];
elseif ($status_filter == '2') $status_text = $translations[$lang]['status_struck_off'];
elseif ($status_filter == 'all') $status_text = $translations[$lang]['all_status'];

// Get data for printing - removed sections join
$query = "SELECT 
    sr.id,
    sr.name,
    sr.father_name,
    sr.mobile,
    sr.reg_no,
    sr.guardian_name,
    sr.guardian_mobile,
    sr.guardian_cnic,
    sr.status,
    c.title AS class_title,
    ses.title AS session_title,
    vc.title AS village_council_title
FROM student_registration sr
LEFT JOIN (
    SELECT sc1.student_registration_id, sc1.class_id, sc1.session_id
    FROM student_class sc1
    INNER JOIN (
        SELECT student_registration_id, MAX(id) AS max_id
        FROM student_class
        GROUP BY student_registration_id
    ) sc2 ON sc1.id = sc2.max_id
) sc ON sr.id = sc.student_registration_id
LEFT JOIN classes c ON sc.class_id = c.id
LEFT JOIN sessions ses ON sc.session_id = ses.id
LEFT JOIN village_councils vc ON sr.village_council_id = vc.id
$where_clause
ORDER BY sr.id DESC";

$result = $conn->query($query);
$total_students = $result ? $result->num_rows : 0;

// Build language switcher URL
$current_query = $_GET;
$current_query['lang'] = 'en';
$en_url = $_SERVER['PHP_SELF'] . '?' . http_build_query($current_query);
$current_query['lang'] = 'ur';
$ur_url = $_SERVER['PHP_SELF'] . '?' . http_build_query($current_query);
?>

<!DOCTYPE html>
<html lang="<?php echo $lang; ?>" dir="<?php echo ($lang == 'ur') ? 'rtl' : 'ltr'; ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $translations[$lang]['print_title']; ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Nastaliq+Urdu&family=Noto+Sans+Arabic&family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Inter', sans-serif;
            padding: 30px;
            background: white;
        }
        
        <?php if ($lang == 'ur'): ?>
        body, .table, .filter-info, .print-header, .print-footer, .language-switcher {
            font-family: 'Noto Nastaliq Urdu', 'Noto Sans Arabic', 'Inter', sans-serif;
            text-align: right;
            direction: rtl;
        }
        
        .filter-badge {
            margin-left: 5px;
            margin-right: 0;
        }
        
        .table th, .table td {
            text-align: right;
        }
        
        .print-footer .text-right {
            text-align: left !important;
        }
        
        .language-switcher {
            left: auto;
            right: 20px;
        }
        
        <?php endif; ?>
        
        /* Language Switcher */
        .language-switcher {
            position: fixed;
            top: 20px;
            right: 20px;
            z-index: 1001;
            background: white;
            padding: 8px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            display: flex;
            gap: 8px;
        }
        
        .language-switcher .btn {
            padding: 8px 16px;
            font-size: 13px;
            font-weight: 500;
            border-radius: 6px;
            transition: all 0.3s ease;
        }
        
        .language-switcher .btn:hover {
            transform: translateY(-1px);
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }
        
        .language-switcher .btn.active {
            background: #667eea;
            color: white;
            border-color: #667eea;
        }
        
        .print-header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #667eea;
        }
        
        .school-name {
            font-size: 26px;
            font-weight: 700;
            color: #2c3e50;
            margin-bottom: 5px;
            line-height: 1.4;
        }
        
        .school-address {
            font-size: 14px;
            color: #7f8c8d;
            margin-bottom: 15px;
        }
        
        .print-title {
            font-size: 20px;
            font-weight: 600;
            color: #667eea;
            margin-bottom: 10px;
        }
        
        .print-subtitle {
            font-size: 13px;
            color: #666;
            margin-bottom: 5px;
        }
        
        .filter-info {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
            font-size: 13px;
        }
        
        .filter-badge {
            background: #667eea;
            color: white;
            padding: 3px 8px;
            border-radius: 12px;
            margin-right: 5px;
            display: inline-block;
            margin-bottom: 5px;
            font-size: 12px;
        }
        
        .table {
            font-size: 12px;
        }
        
        .table th {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            font-weight: 600;
            padding: 10px;
            white-space: nowrap;
        }
        
        .table td {
            padding: 8px;
            vertical-align: middle;
        }
        
        .status-badge {
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 11px;
            font-weight: 600;
            display: inline-block;
        }
        
        .status-active {
            background: #d4edda;
            color: #155724;
        }
        
        .status-leave {
            background: #fff3cd;
            color: #856404;
        }
        
        .status-struck {
            background: #f8d7da;
            color: #721c24;
        }
        
        .print-footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #dee2e6;
            font-size: 12px;
            color: #666;
        }
        
        @media print {
            .no-print {
                display: none !important;
            }
            body {
                padding: 0;
            }
            .language-switcher {
                display: none;
            }
            .table th {
                background: #667eea !important;
                color: white !important;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }
            .status-active, .status-leave, .status-struck {
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }
        }
        
        .print-button {
            position: fixed;
            bottom: 30px;
            right: 30px;
            z-index: 1000;
            display: flex;
            gap: 10px;
        }
        
        <?php if ($lang == 'ur'): ?>
        .print-button {
            left: 30px;
            right: auto;
        }
        <?php endif; ?>
        
        .btn {
            padding: 10px 20px;
            font-size: 14px;
            font-weight: 500;
            border-radius: 6px;
            transition: all 0.3s ease;
        }
        
        .btn:hover {
            transform: translateY(-1px);
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }
        
        .btn-lg {
            padding: 12px 24px;
            font-size: 16px;
        }
        
        @media (max-width: 768px) {
            body {
                padding: 15px;
            }
            .table {
                font-size: 10px;
            }
            .btn-lg {
                padding: 8px 16px;
                font-size: 14px;
            }
            .school-name {
                font-size: 18px;
            }
            .language-switcher {
                top: 10px;
                right: 10px;
                padding: 5px;
            }
            .language-switcher .btn {
                padding: 5px 10px;
                font-size: 11px;
            }
        }
        
        .student-name {
            font-weight: 600;
            color: #2c3e50;
        }
        
        .info-text {
            color: #7f8c8d;
            font-size: 11px;
        }
    </style>
</head>
<body>
    <!-- Language Switcher -->
    <div class="language-switcher no-print">
        <a href="<?php echo htmlspecialchars($en_url); ?>" class="btn btn-default btn-sm <?php echo ($lang == 'en') ? 'active' : ''; ?>">
            <span class="glyphicon glyphicon-globe"></span> English
        </a>
        <a href="<?php echo htmlspecialchars($ur_url); ?>" class="btn btn-default btn-sm <?php echo ($lang == 'ur') ? 'active' : ''; ?>">
            <span class="glyphicon glyphicon-globe"></span> اردو
        </a>
    </div>

    <!-- Print Buttons -->
    <div class="print-button no-print">
        <button onclick="window.print();" class="btn btn-lg btn-success">
            <i class="fas fa-print"></i> <?php echo $translations[$lang]['print']; ?>
        </button>
        <button onclick="window.close();" class="btn btn-lg btn-secondary">
            <i class="fas fa-times"></i> <?php echo $translations[$lang]['close']; ?>
        </button>
    </div>

    <!-- Print Header with School Name -->
    <div class="print-header">
        <div class="school-name">
            <?php echo $translations[$lang]['school_name']; ?>
        </div>
        <div class="school-address">
            <?php echo $translations[$lang]['school_address']; ?>
        </div>
        <div class="print-title">
            <?php echo $translations[$lang]['print_title']; ?>
        </div>
        <div class="print-subtitle">
            <?php echo $translations[$lang]['print_date']; ?>: <?php echo date('d F Y, h:i A'); ?>
        </div>
        <div class="print-subtitle">
            <?php echo $translations[$lang]['generated_by']; ?>: <?php echo htmlspecialchars($_SESSION['username'] ?? 'Admin'); ?>
        </div>
    </div>

    <!-- Filter Information -->
    <div class="filter-info">
        <strong><?php echo $translations[$lang]['filter_criteria']; ?>:</strong><br>
        <?php if (!empty($search)): ?>
            <span class="filter-badge"><?php echo $translations[$lang]['search']; ?>: <?php echo htmlspecialchars($search); ?></span>
        <?php endif; ?>
        
        <?php if ($class_filter > 0): ?>
            <span class="filter-badge"><?php echo $translations[$lang]['class']; ?>: <?php echo htmlspecialchars($class_name); ?></span>
        <?php else: ?>
            <span class="filter-badge"><?php echo $translations[$lang]['all_classes']; ?></span>
        <?php endif; ?>
        
        <?php if ($village_filter > 0): ?>
            <span class="filter-badge"><?php echo $translations[$lang]['village']; ?>: <?php echo htmlspecialchars($village_name); ?></span>
        <?php else: ?>
            <span class="filter-badge"><?php echo $translations[$lang]['all_villages']; ?></span>
        <?php endif; ?>
        
        <span class="filter-badge"><?php echo $translations[$lang]['status_filter']; ?>: <?php echo $status_text; ?></span>
        
        <span class="filter-badge"><?php echo $translations[$lang]['total_students']; ?>: <?php echo $total_students; ?></span>
    </div>

    <!-- Student List Table -->
    <?php if ($result && $result->num_rows > 0): ?>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th width="5%">#</th>
                    <th width="20%"><?php echo $translations[$lang]['student_information']; ?></th>
                    <th width="20%"><?php echo $translations[$lang]['guardian_information']; ?></th>
                    <th width="15%"><?php echo $translations[$lang]['class_session']; ?></th>
                    <th width="15%"><?php echo $translations[$lang]['village_council']; ?></th>
                    <th width="10%"><?php echo $translations[$lang]['status']; ?></th>
                    <th width="15%"><?php echo $translations[$lang]['reg_no_label']; ?></th>
                </tr>
            </thead>
            <tbody>
                <?php 
                $count = 1;
                while ($row = $result->fetch_assoc()): 
                    $status_class = '';
                    $status_text_display = '';
                    if ($row['status'] == 0) {
                        $status_class = 'status-active';
                        $status_text_display = $translations[$lang]['status_active'];
                    } elseif ($row['status'] == 1) {
                        $status_class = 'status-leave';
                        $status_text_display = $translations[$lang]['status_leave'];
                    } elseif ($row['status'] == 2) {
                        $status_class = 'status-struck';
                        $status_text_display = $translations[$lang]['status_struck_off'];
                    } else {
                        $status_class = 'status-active';
                        $status_text_display = $translations[$lang]['status_active'];
                    }
                ?>
                <tr>
                    <td class="text-center"><?php echo $count++; ?></td>
                    <td>
                        <div class="student-name"><?php echo htmlspecialchars($row['name']); ?></div>
                        <div class="info-text"><?php echo $translations[$lang]['father_name_label']; ?> <?php echo htmlspecialchars($row['father_name']); ?></div>
                        <div class="info-text"><?php echo $translations[$lang]['mobile_label']; ?> <?php echo htmlspecialchars($row['mobile']); ?></div>
                    </td>
                    <td>
                        <div class="student-name"><?php echo htmlspecialchars($row['guardian_name']); ?></div>
                        <div class="info-text"><?php echo $translations[$lang]['guardian_mobile_label']; ?> <?php echo htmlspecialchars($row['guardian_mobile']); ?></div>
                        <div class="info-text"><?php echo $translations[$lang]['guardian_cnic_label']; ?> <?php echo htmlspecialchars($row['guardian_cnic']); ?></div>
                    </td>
                    <td>
                        <div><strong><?php echo htmlspecialchars($row['class_title'] ?? 'Not Assigned'); ?></strong></div>
                        <div class="info-text"><?php echo $translations[$lang]['session_label']; ?> <?php echo htmlspecialchars($row['session_title'] ?? 'Not Assigned'); ?></div>
                    </td>
                    <td><?php echo htmlspecialchars($row['village_council_title'] ?? 'N/A'); ?></td>
                    <td class="text-center">
                        <span class="status-badge <?php echo $status_class; ?>">
                            <?php echo $status_text_display; ?>
                        </span>
                    </td>
                    <td><?php echo htmlspecialchars($row['reg_no']); ?></td>
                </tr>
                <?php endwhile; ?>
            </tbody>
        </table>
    </div>
    
    <!-- Footer -->
    <div class="print-footer">
        <div class="row">
            <div class="col-md-6">
                <strong><?php echo $translations[$lang]['total_students']; ?>:</strong> <?php echo $total_students; ?>
            </div>
            <div class="col-md-6 text-right">
                <strong><?php echo $translations[$lang]['report_id']; ?>:</strong> RPT-<?php echo date('YmdHis'); ?>
            </div>
        </div>
    </div>
    <?php else: ?>
    <div class="alert alert-info text-center">
        <i class="fas fa-info-circle" style="font-size: 24px;"></i>
        <h4><?php echo $translations[$lang]['no_records']; ?></h4>
    </div>
    <?php endif; ?>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</body>
</html>
<?php $conn->close(); ?>