<?php 
header('Content-Type: text/html; charset=utf-8');
require_once('security.php');

// Initialize session if not started
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}

// Language handling
if (isset($_GET['lang'])) {
    $_SESSION['lang'] = $_GET['lang'];
} elseif (!isset($_SESSION['lang'])) {
    $_SESSION['lang'] = 'en'; // Default to English
}

$lang = $_SESSION['lang'];

// Language strings
$translations = [
    'en' => [
        'title' => 'Student List',
        'list_title' => 'Student List',
        'no_records' => 'No students found.',
        'sr_no' => '#',
        'student_id' => 'Student ID',
        'actions' => 'Actions',
        'edit' => 'Edit',
        'print_registration_form' => 'Print Form',
        'print_list' => 'Print List',
        'print_filtered_list' => 'Print Current List',
        'father_name_label' => 'Father Name:',
        'mobile_label' => 'Mobile:',
        'reg_no_label' => 'Reg No:',
        'guardian_mobile_label' => 'Guardian Mobile:',
        'guardian_cnic_label' => 'Guardian CNIC:',
        'class_or_course' => 'Class/Course:',
        'session_label' => 'Session:',
        'search_placeholder' => 'Search by name, father name, mobile, ID...',
        'reset_button' => 'Reset',
        'add_new_student' => 'Add Student',
        'delete_confirm' => 'Are you sure you want to delete this student record?',
        'delete_success' => 'Student deleted successfully!',
        'error' => 'Error: ',
        'filter_by_class' => 'Filter by Class',
        'filter_by_village' => 'Filter by Village Council',
        'filter_by_status' => 'Filter by Status',
        'filter_by_branch' => 'Filter by Branch',
        'all_classes' => 'All Classes',
        'all_villages' => 'All Village Councils',
        'all_branches' => 'All Branches',
        'all_status' => 'All Students',
        'status_active' => 'Active',
        'status_leave' => 'Leave',
        'status_struck_off' => 'Struck Off',
        'active_students' => 'Active Students',
        'status' => 'Status',
        'print_date' => 'Print Date',
        'total_students' => 'Total Students',
        'generated_by' => 'Generated by',
        'print_title' => 'Student List Report',
        'village_council' => 'Village Council',
        'branch' => 'Branch',
        'update_status' => 'Update Status',
        'select_new_status' => 'Select New Status',
        'status_updated' => 'Student status updated successfully!',
        'status_update_confirm' => 'Are you sure you want to change this student\'s status?',
        'status_update_error' => 'Error updating status: ',
        'change_status' => 'Change Status',
        'current_status' => 'Current Status',
        'collect_fee' => 'Collect Fee',
        'withdrawal' => 'Withdrawal',
        'withdrawal_confirm' => 'Are you sure you want to withdraw this student? This will set the status to Leave.',
        'withdrawal_success' => 'Student withdrawal successful! Status set to Leave.',
        'withdrawal_error' => 'Error processing withdrawal: ',
        'toggle_type' => 'Toggle Regular/Hostilized',
        'toggle_success' => 'Student type toggled successfully!',
        'toggle_confirm' => 'Are you sure you want to toggle this student\'s type?',
        'regular' => 'Regular',
        'hostilized' => 'Hostilized',
        'student_type_label' => 'Student Type',
        'toggle_student_type' => 'Toggle Type',
        'loading_more' => 'Loading more students...',
        'no_more_students' => 'No more students to load.',
        'view_details' => 'View Details',
        'student_info' => 'Student Info',
        'guardian_info' => 'Guardian Info',
        'tap_to_expand' => 'Tap to expand',
        'tap_to_collapse' => 'Tap to collapse'
    ],
    'ur' => [
        'title' => 'طلبہ کی فہرست',
        'list_title' => 'طلباء کی فہرست',
        'no_records' => 'کوئی طالب علم نہیں ملا',
        'sr_no' => 'نمبر',
        'student_id' => 'طالب علم کا شناختی نمبر',
        'actions' => 'اعمال',
        'edit' => 'ترمیم',
        'print_registration_form' => 'فارم پرنٹ کریں',
        'print_list' => 'فہرست پرنٹ کریں',
        'print_filtered_list' => 'موجودہ فہرست پرنٹ کریں',
        'father_name_label' => 'والد کا نام:',
        'mobile_label' => 'موبائل نمبر:',
        'reg_no_label' => 'رجسٹریشن نمبر:',
        'guardian_mobile_label' => 'سرپرست کا موبائل:',
        'guardian_cnic_label' => 'سرپرست کا شناختی کارڈ:',
        'class_or_course' => 'کلاس/کورس:',
        'session_label' => 'سیشن:',
        'search_placeholder' => 'نام، والد کا نام، موبائل، شناختی نمبر سے تلاش کریں...',
        'reset_button' => 'ری سیٹ کریں',
        'add_new_student' => 'نیا طالب علم',
        'delete_confirm' => 'کیا آپ واقعی اس طالب علم کا ریکارڈ حذف کرنا چاہتے ہیں؟',
        'delete_success' => 'طالب علم کامیابی سے حذف ہو گیا',
        'error' => 'خرابی: ',
        'filter_by_class' => 'کلاس کے مطابق فلٹر کریں',
        'filter_by_village' => 'ویلیج کونسل کے مطابق فلٹر کریں',
        'filter_by_status' => 'اسٹیٹس کے مطابق فلٹر کریں',
        'filter_by_branch' => 'برانچ کے مطابق فلٹر کریں',
        'all_classes' => 'تمام کلاسیں',
        'all_villages' => 'تمام ویلیج کونسلیں',
        'all_branches' => 'تمام برانچز',
        'all_status' => 'تمام طلبہ',
        'status_active' => 'فعال',
        'status_leave' => 'چھٹی پر',
        'status_struck_off' => 'خارج شدہ',
        'active_students' => 'فعال طلبہ',
        'status' => 'اسٹیٹس',
        'print_date' => 'پرنٹ کی تاریخ',
        'total_students' => 'کل طلبہ',
        'generated_by' => 'تیار کردہ',
        'print_title' => 'طلبہ کی فہرست کی رپورٹ',
        'village_council' => 'ویلیج کونسل',
        'branch' => 'برانچ',
        'update_status' => 'اسٹیٹس اپ ڈیٹ کریں',
        'select_new_status' => 'نیا اسٹیٹس منتخب کریں',
        'status_updated' => 'طالب علم کا اسٹیٹس کامیابی سے اپ ڈیٹ ہو گیا',
        'status_update_error' => 'اسٹیٹس اپ ڈیٹ کرنے میں خرابی: ',
        'change_status' => 'اسٹیٹس تبدیل کریں',
        'current_status' => 'موجودہ اسٹیٹس',
        'collect_fee' => 'فیس جمع کریں',
        'withdrawal' => 'خارج کریں',
        'withdrawal_confirm' => 'کیا آپ واقعی اس طالب علم کو خارج کرنا چاہتے ہیں؟ اس کا اسٹیٹس چھٹی پر ہو جائے گا۔',
        'withdrawal_success' => 'طالب علم کامیابی سے خارج کر دیا گیا! اسٹیٹس چھٹی پر کر دیا گیا۔',
        'withdrawal_error' => 'خارج کرنے میں خرابی: ',
        'toggle_type' => 'ریگولر/ہوسٹلائزڈ ٹوگل کریں',
        'toggle_success' => 'طالب علم کی قسم کامیابی سے تبدیل ہو گئی!',
        'toggle_confirm' => 'کیا آپ واقعی اس طالب علم کی قسم تبدیل کرنا چاہتے ہیں؟',
        'regular' => 'ریگولر',
        'hostilized' => 'ہوسٹلائزڈ',
        'student_type_label' => 'طالب علم کی قسم',
        'toggle_student_type' => 'قسم تبدیل کریں',
        'loading_more' => 'مزید طلبہ لوڈ ہو رہے ہیں...',
        'no_more_students' => 'مزید طلبہ لوڈ کرنے کے لیے دستیاب نہیں ہیں۔',
        'view_details' => 'تفصیلات دیکھیں',
        'student_info' => 'طالب علم کی معلومات',
        'guardian_info' => 'سرپرست کی معلومات',
        'tap_to_expand' => 'تفصیلات کے لیے تھپتھپائیں',
        'tap_to_collapse' => 'بند کرنے کے لیے تھپتھپائیں'
    ]
];

// Create database connection
require_once('conn_inc.php');

// Handle student type toggle - FIXED WITH CORRECT CASE (Regular/Hostilized)
if (isset($_GET['toggle_type'])) {
    $id = intval($_GET['toggle_type']);
    
    $stmt = $conn->prepare("UPDATE student_registration SET student_type = 
                            CASE 
                                WHEN student_type = 'Regular' THEN 'Hostilized'
                                WHEN student_type = 'Hostilized' THEN 'Regular'
                                ELSE 'Regular'
                            END 
                            WHERE id = ?");
    $stmt->bind_param("i", $id);
    
    if ($stmt->execute()) {
        if ($stmt->affected_rows > 0) {
            $_SESSION['message'] = $translations[$lang]['toggle_success'];
            $_SESSION['message_type'] = 'success';
        } else {
            $_SESSION['message'] = $translations[$lang]['error'] . "No changes made. Student ID may not exist.";
            $_SESSION['message_type'] = 'warning';
        }
    } else {
        $_SESSION['message'] = $translations[$lang]['error'] . $stmt->error;
        $_SESSION['message_type'] = 'danger';
    }
    
    $stmt->close();
    
    $redirect_url = $_SERVER['PHP_SELF'];
    $params = [];
    if (!empty($_GET['search'])) $params['search'] = $_GET['search'];
    if (!empty($_GET['class_filter'])) $params['class_filter'] = $_GET['class_filter'];
    if (!empty($_GET['village_filter'])) $params['village_filter'] = $_GET['village_filter'];
    if (!empty($_GET['branch_filter'])) $params['branch_filter'] = $_GET['branch_filter'];
    if (!empty($_GET['status_filter'])) $params['status_filter'] = $_GET['status_filter'];
    if (!empty($_GET['lang'])) $params['lang'] = $_GET['lang'];
    if (!empty($params)) { $redirect_url .= "?" . http_build_query($params); }
    header("Location: " . $redirect_url);
    exit();
}

// Handle withdrawal (status update to 1 in student_class table)
if (isset($_POST['withdrawal'])) {
    $student_id = intval($_POST['student_id']);
    $new_status = 1;
    
    $stmt = $conn->prepare("UPDATE student_class SET status = ? WHERE student_registration_id = ? ORDER BY id DESC LIMIT 1");
    $stmt->bind_param("ii", $new_status, $student_id);
    
    if ($stmt->execute() && $stmt->affected_rows > 0) {
        $_SESSION['message'] = $translations[$lang]['withdrawal_success'];
        $_SESSION['message_type'] = 'success';
    } else {
        $stmt2 = $conn->prepare("INSERT INTO student_class (student_registration_id, status) VALUES (?, ?)");
        $stmt2->bind_param("ii", $student_id, $new_status);
        if ($stmt2->execute()) {
            $_SESSION['message'] = $translations[$lang]['withdrawal_success'];
            $_SESSION['message_type'] = 'success';
        } else {
            $_SESSION['message'] = $translations[$lang]['withdrawal_error'] . $stmt->error;
            $_SESSION['message_type'] = 'danger';
        }
        $stmt2->close();
    }
    
    $stmt->close();
    
    $redirect_url = $_SERVER['PHP_SELF'];
    $params = [];
    if (!empty($_GET['search'])) $params['search'] = $_GET['search'];
    if (!empty($_GET['class_filter'])) $params['class_filter'] = $_GET['class_filter'];
    if (!empty($_GET['village_filter'])) $params['village_filter'] = $_GET['village_filter'];
    if (!empty($_GET['branch_filter'])) $params['branch_filter'] = $_GET['branch_filter'];
    if (!empty($_GET['status_filter'])) $params['status_filter'] = $_GET['status_filter'];
    if (!empty($_GET['lang'])) $params['lang'] = $_GET['lang'];
    if (!empty($params)) { $redirect_url .= "?" . http_build_query($params); }
    header("Location: " . $redirect_url);
    exit();
}

// Handle student deletion
if (isset($_GET['delete'])) {
    $id = intval($_GET['delete']);
    $stmt = $conn->prepare("DELETE FROM student_registration WHERE id = ?");
    $stmt->bind_param("i", $id);
    
    if ($stmt->execute()) {
        $_SESSION['message'] = $translations[$lang]['delete_success'];
        $_SESSION['message_type'] = 'success';
    } else {
        $_SESSION['message'] = $translations[$lang]['error'] . $stmt->error;
        $_SESSION['message_type'] = 'danger';
    }
    
    $stmt->close();
    
    $redirect_url = $_SERVER['PHP_SELF'];
    $params = [];
    if (!empty($_GET['search'])) $params['search'] = $_GET['search'];
    if (!empty($_GET['class_filter'])) $params['class_filter'] = $_GET['class_filter'];
    if (!empty($_GET['village_filter'])) $params['village_filter'] = $_GET['village_filter'];
    if (!empty($_GET['branch_filter'])) $params['branch_filter'] = $_GET['branch_filter'];
    if (!empty($_GET['status_filter'])) $params['status_filter'] = $_GET['status_filter'];
    if (!empty($_GET['lang'])) $params['lang'] = $_GET['lang'];
    if (!empty($params)) { $redirect_url .= "?" . http_build_query($params); }
    header("Location: " . $redirect_url);
    exit();
}

// Handle AJAX lazy loading request
$is_ajax_request = isset($_GET['ajax_load']) && $_GET['ajax_load'] == '1';

// Fetch filter options
$classes = [];
$village_councils = [];
$branches = [];

$class_filter_query = $conn->query("SELECT c.id AS class_id, c.title AS class_title FROM classes c ORDER BY c.title");
while ($row = $class_filter_query->fetch_assoc()) {
    $classes[$row['class_id']] = $row['class_title'];
}

$village_filter_query = $conn->query("SELECT id, title FROM village_councils ORDER BY title");
while ($row = $village_filter_query->fetch_assoc()) {
    $village_councils[$row['id']] = $row['title'];
}

$branch_filter_query = $conn->query("SELECT id, title FROM branches ORDER BY title");
while ($row = $branch_filter_query->fetch_assoc()) {
    $branches[$row['id']] = $row['title'];
}

// Handle filters
$search = isset($_GET['search']) ? mysqli_real_escape_string($conn, $_GET['search']) : '';
$class_filter = isset($_GET['class_filter']) ? intval($_GET['class_filter']) : 0;
$village_filter = isset($_GET['village_filter']) ? intval($_GET['village_filter']) : 0;
$branch_filter = isset($_GET['branch_filter']) ? intval($_GET['branch_filter']) : 0;
$status_filter = isset($_GET['status_filter']) ? $_GET['status_filter'] : '0';

// Lazy loading parameters
$offset = isset($_GET['offset']) ? intval($_GET['offset']) : 0;
$limit = 20;

// Build WHERE clause
$where_conditions = [];
if (!empty($search)) {
    $where_conditions[] = "(sr.name LIKE '%$search%' OR sr.father_name LIKE '%$search%' OR sr.mobile LIKE '%$search%' OR sr.reg_no LIKE '%$search%' OR sr.guardian_name LIKE '%$search%' OR sr.guardian_mobile LIKE '%$search%' OR sr.guardian_cnic LIKE '%$search%' OR sr.id LIKE '%$search%')";
}
if ($class_filter > 0)   { $where_conditions[] = "sc.class_id = '$class_filter'"; }
if ($village_filter > 0) { $where_conditions[] = "sr.village_council_id = '$village_filter'"; }
if ($branch_filter > 0)  { $where_conditions[] = "sr.branch_id = '$branch_filter'"; }
if ($status_filter !== 'all') { $where_conditions[] = "sc.status = '$status_filter'"; }

$where_clause = !empty($where_conditions) ? 'WHERE ' . implode(' AND ', $where_conditions) : '';

// Total count
$count_query = "SELECT COUNT(*) as total FROM student_registration sr
LEFT JOIN (
    SELECT sc1.student_registration_id, sc1.class_id, sc1.session_id, sc1.status
    FROM student_class sc1
    INNER JOIN (SELECT student_registration_id, MAX(id) AS max_id FROM student_class GROUP BY student_registration_id) sc2 ON sc1.id = sc2.max_id
) sc ON sr.id = sc.student_registration_id
$where_clause";

$count_result = $conn->query($count_query);
$total_count_row = $count_result->fetch_assoc();
$total_records = $total_count_row['total'];

// Main query
$query = "SELECT sr.id, sr.name, sr.father_name, sr.mobile, sr.reg_no, sr.guardian_name, sr.guardian_mobile, sr.guardian_cnic, sr.village_council_id, sr.branch_id, sr.student_type,
    COALESCE(sc.status, 0) AS status,
    c.title AS class_title, ses.title AS session_title, vc.title AS village_council_title, b.title AS branch_name
FROM student_registration sr
LEFT JOIN (
    SELECT sc1.student_registration_id, sc1.class_id, sc1.session_id, sc1.status
    FROM student_class sc1
    INNER JOIN (SELECT student_registration_id, MAX(id) AS max_id FROM student_class GROUP BY student_registration_id) sc2 ON sc1.id = sc2.max_id
) sc ON sr.id = sc.student_registration_id
LEFT JOIN classes c ON sc.class_id = c.id
LEFT JOIN sessions ses ON sc.session_id = ses.id
LEFT JOIN village_councils vc ON sr.village_council_id = vc.id
LEFT JOIN branches b ON sr.branch_id = b.id
$where_clause
ORDER BY sr.id DESC
LIMIT $offset, $limit";

$result = $conn->query($query);
$current_batch_count = $result ? $result->num_rows : 0;
$has_more = ($offset + $current_batch_count) < $total_records;

// AJAX response
if ($is_ajax_request) {
    $students_data = [];
    while ($row = $result->fetch_assoc()) {
        $status_class = ($row['status'] == 1) ? 'status-leave' : (($row['status'] == 2) ? 'status-struck' : 'status-active');
        $status_text  = ($row['status'] == 1) ? $translations[$lang]['status_leave'] : (($row['status'] == 2) ? $translations[$lang]['status_struck_off'] : $translations[$lang]['status_active']);
        $student_type = isset($row['student_type']) ? $row['student_type'] : 'Regular';
        $type_class   = ($student_type == 'Regular') ? 'type-regular' : 'type-hostilized';
        $type_text    = ($student_type == 'Regular') ? $translations[$lang]['regular'] : $translations[$lang]['hostilized'];
        $students_data[] = [
            'id'                  => $row['id'],
            'name'                => htmlspecialchars($row['name']),
            'father_name'         => htmlspecialchars($row['father_name']),
            'mobile'              => htmlspecialchars($row['mobile']),
            'reg_no'              => htmlspecialchars($row['reg_no']),
            'guardian_name'       => htmlspecialchars($row['guardian_name']),
            'guardian_mobile'     => htmlspecialchars($row['guardian_mobile']),
            'guardian_cnic'       => htmlspecialchars($row['guardian_cnic']),
            'class_title'         => htmlspecialchars($row['class_title'] ?? 'Not Assigned'),
            'session_title'       => htmlspecialchars($row['session_title'] ?? 'Not Assigned'),
            'branch_name'         => htmlspecialchars($row['branch_name'] ?? 'N/A'),
            'village_council_title' => htmlspecialchars($row['village_council_title'] ?? 'N/A'),
            'status_class'        => $status_class,
            'status_text'         => $status_text,
            'type_class'          => $type_class,
            'type_text'           => $type_text,
            'student_type'        => $student_type,
        ];
    }
    header('Content-Type: application/json');
    echo json_encode(['success' => true, 'students' => $students_data, 'has_more' => $has_more, 'offset' => $offset + $current_batch_count, 'total_records' => $total_records]);
    exit();
}

$total_students = $total_records;

$print_query_string = http_build_query(['search' => $search, 'class_filter' => $class_filter, 'village_filter' => $village_filter, 'branch_filter' => $branch_filter, 'status_filter' => $status_filter, 'lang' => $lang]);

$js_translations = [
    'delete_confirm'      => $translations[$lang]['delete_confirm'],
    'withdrawal_confirm'  => $translations[$lang]['withdrawal_confirm'],
    'toggle_confirm'      => $translations[$lang]['toggle_confirm'],
    'loading_more'        => $translations[$lang]['loading_more'],
    'no_more_students'    => $translations[$lang]['no_more_students'],
];
?>
<!DOCTYPE html>
<html lang="<?php echo $lang; ?>" dir="<?php echo ($lang == 'ur') ? 'rtl' : 'ltr'; ?>">
<head>
    <title><?php echo $translations[$lang]['title']; ?></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=yes, viewport-fit=cover">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Nastaliq+Urdu&family=Noto+Sans+Arabic&display=swap" rel="stylesheet">
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; overflow-x: hidden; background: #f4f6f9; margin: 0; padding: 0; }
        .container { width: 100%; padding-right: 15px; padding-left: 15px; margin-right: auto; margin-left: auto; }
        @media (min-width: 576px) { .container { max-width: 540px; } }
        @media (min-width: 768px) { .container { max-width: 720px; } }
        @media (min-width: 992px) { .container { max-width: 960px; } }
        @media (min-width: 1200px) { .container { max-width: 1140px; } }

        <?php if ($lang == 'ur'): ?>
        body, .form-control, .btn, .alert, .navbar-nav, .panel-title,
        .table, .label, .badge, .modal-content, .status-description,
        input, select, textarea, .info-label, .info-value, .student-name-card,
        .student-class-card, .collapsed-info, .expanded-content {
            font-family: 'Noto Nastaliq Urdu', 'Noto Sans Arabic', 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-size: 15px; line-height: 1.8; text-align: right; direction: rtl;
        }
        .form-control { padding: 10px 12px !important; text-align: right; font-size: 15px !important; height: 44px !important; }
        select.form-control { background-position: left 10px center; padding-right: 12px !important; padding-left: 30px !important; }
        .panel-heading .panel-title { color: white !important; text-align: right; }
        .table th, .table td { text-align: right; vertical-align: middle; }
        .search-input-wrapper .form-control { padding-left: 35px; padding-right: 12px; }
        .search-input-wrapper .search-icon { left: 10px; right: auto; }
        .btn-action .glyphicon { margin-left: 8px; margin-right: 0; }
        .language-switcher .btn { margin-left: 5px; margin-right: 0; }
        .results-info { text-align: right; }
        .type-badge { margin-right: 8px; margin-left: 0; }
        .student-name-row { justify-content: flex-start; }
        .expand-indicator { margin-left: 0; margin-right: auto; }
        .info-row { flex-direction: row; }
        .info-label { text-align: right; width: 40%; }
        .info-value { text-align: left; width: 60%; }
        .filter-row .form-group label { text-align: right; display: block; font-size: 14px; margin-bottom: 8px; }
        .filter-row .form-control { font-size: 14px !important; padding: 10px 12px !important; }
        .btn-group-actions { justify-content: flex-start; }
        .pull-right { float: left !important; }
        <?php else: ?>
        .panel-heading .panel-title { color: white !important; }
        body, .form-control, .btn, .alert, .navbar-nav { text-align: left; direction: ltr; }
        .table th, .table td { text-align: left; }
        .search-input-wrapper .form-control { padding-right: 35px; }
        .search-input-wrapper .search-icon { right: 10px; left: auto; }
        .btn-action .glyphicon { margin-right: 8px; }
        .language-switcher .btn { margin-right: 5px; }
        <?php endif; ?>

        .panel { border-radius: 8px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .panel-info .panel-heading { background: #337ab7; border-color: #17a2b8; }
        .panel-heading .panel-title { font-weight: 600; font-size: 22px; color: white !important; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 10px; }

        .registration-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; flex-wrap: nowrap; gap: 10px; }
        .student-list-btn { padding: 6px 12px !important; font-size: 18px !important; font-weight: 600 !important; transition: all 0.3s ease !important; background-color: #5cb85c !important; border-color: #5cb85c !important; box-shadow: 0 1px 3px rgba(0,0,0,0.1) !important; display: inline-flex; align-items: center; gap: 6px; white-space: nowrap; border-radius: 4px !important; color: white !important; text-decoration: none; }
        .student-list-btn:hover { transform: translateY(-1px); box-shadow: 0 2px 6px rgba(0,0,0,0.15); background-color: #4cae4c !important; color: white !important; text-decoration: none; }
        .student-list-btn .glyphicon { font-size: 14px !important; }
        .language-switcher { display: flex !important; gap: 8px; flex-wrap: nowrap; }
        .language-switcher .btn { padding: 6px 12px !important; font-size: 18px !important; font-weight: 600 !important; border-radius: 4px !important; transition: all 0.3s ease !important; background-color: #337ab7 !important; border: 1px solid #ddd !important; color: white !important; white-space: nowrap; }
        .language-switcher .btn:hover { transform: translateY(-1px); box-shadow: 0 2px 6px rgba(0,0,0,0.1); background-color: #286090 !important; }
        .language-switcher .btn.active { background-color: #2e6da4 !important; border-color: #2e6da4 !important; font-weight: 600; }
        .language-switcher .btn:not(.active) { background-color: #f5f5f5 !important; color: #333 !important; border-color: #ccc !important; }

        @media (max-width: 767px) {
            .registration-header { flex-direction: row; justify-content: space-between; align-items: center; gap: 6px; }
            .student-list-btn { padding: 8px 14px !important; font-size: 13px !important; gap: 5px; flex-shrink: 0; }
            .student-list-btn .glyphicon { font-size: 13px !important; }
            .language-switcher { gap: 9px; flex-shrink: 1; }
            .language-switcher .btn { padding: 8px 14px !important; font-size: 13px !important; }
        }
        @media (max-width: 480px) {
            .registration-header { gap: 5px; }
            .student-list-btn { font-size: 14px !important; width: 160px !important; }
            .student-list-btn .glyphicon { font-size: 11px !important; }
            .language-switcher .btn { padding: 6px 10px !important; font-size: 14px !important; }
        }

        .search-box { background: #f9f9f9; padding: 20px; border-radius: 8px; margin-bottom: 20px; border: 1px solid #e0e0e0; }
        .filter-row { margin-top: 15px; }
        .search-input-wrapper { position: relative; }
        .search-input-wrapper .form-control { font-size: 14px !important; height: 42px; }
        .search-input-wrapper .search-icon { position: absolute; top: 50%; transform: translateY(-50%); color: #999; pointer-events: none; z-index: 5; }

        <?php if ($lang == 'ur'): ?>
        @media (max-width: 767px) {
            .form-control { font-size: 14px !important; padding: 10px 12px !important; height: 46px !important; }
            .search-input-wrapper .form-control { height: 46px !important; font-size: 14px !important; }
            .filter-row .form-group { margin-bottom: 15px; }
            .filter-row .form-control { height: 46px !important; font-size: 14px !important; }
            .btn, .btn-sm, .btn-xs { font-size: 14px !important; padding: 6px 10px !important; }
        }
        <?php endif; ?>

        .results-info { background: #e9ecef; padding: 10px 15px; border-radius: 5px; margin-bottom: 15px; font-size: 14px !important; font-weight: 500; display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 10px; }
        .status-badge { padding: 5px 10px; border-radius: 20px; font-size: 12px; font-weight: 600; display: inline-block; text-align: center; min-width: 80px; }
        .status-active { background: #d4edda; color: #155724; border: 1px solid #c3e6cb; }
        .status-leave { background: #fff3cd; color: #856404; border: 1px solid #ffeeba; }
        .status-struck { background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }
        .type-badge { padding: 5px 10px; border-radius: 20px; font-size: 12px; font-weight: 600; display: inline-block; text-align: center; min-width: 80px; }
        .type-regular { background: #cce5ff; color: #004085; border: 1px solid #b8daff; }
        .type-hostilized { background: #e2e3e5; color: #383d41; border: 1px solid #d6d8db; }
        .branch-item { display: inline-block; background-color: #e9ecef; color: #495057; font-weight: 600; padding: 4px 10px; border-radius: 20px; font-size: 12px; }
        .btn-print { background: linear-gradient(135deg, #28a745 0%, #218838 100%); border: none; color: white; padding: 6px 12px; font-size: 12px; font-weight: 500; border-radius: 6px; }
        .btn-print:hover { background: linear-gradient(135deg, #218838 0%, #1e7e34 100%); color: white; }
        .btn-action { margin: 2px !important; padding: 6px 10px !important; font-size: 11px !important; font-weight: 600 !important; border-radius: 4px !important; transition: all 0.3s ease !important; }
        @media (min-width: 768px) { .btn-action { padding: 8px 12px !important; font-size: 12px !important; } }

        @media (max-width: 767px) {
            .btn-group-actions { display: flex; flex-direction: row; flex-wrap: nowrap; gap: 6px; overflow-x: auto; -webkit-overflow-scrolling: touch; padding-bottom: 5px; }
            .btn-group-actions .btn-action { white-space: nowrap; flex-shrink: 0; margin: 0 !important; padding: 6px 10px !important; font-size: 10px !important; }
            .expanded-actions { display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; overflow-x: auto; -webkit-overflow-scrolling: touch; padding-bottom: 5px; }
            .expanded-actions .btn-action { white-space: nowrap; flex-shrink: 0; margin: 0 !important; padding: 8px 12px !important; font-size: 11px !important; }
        }

        .btn-warning.btn-action { background-color: #ffc107; border-color: #ffc107; color: #212529; }
        .btn-info.btn-action { background-color: #17a2b8; border-color: #17a2b8; }
        .btn-success.btn-action { background-color: #28a745; border-color: #28a745; }
        .btn-danger.btn-action { background-color: #dc3545; border-color: #dc3545; }
        .btn-primary.btn-action { background-color: #007bff; border-color: #007bff; }
        .btn-group-actions { display: inline-flex; flex-direction: row; flex-wrap: wrap; gap: 8px; justify-content: center; }

        .table-responsive { overflow-x: auto; -webkit-overflow-scrolling: touch; margin-bottom: 20px; }
        .table { width: 100%; margin-bottom: 0; border-collapse: collapse; }
        .table th { font-size: 14px; font-weight: 700; color: #fff !important; background-color: #34495e !important; padding: 12px !important; border: 1px solid #e2e8f0 !important; }
        .table td { padding: 10px !important; border: 1px solid #e2e8f0 !important; vertical-align: middle; font-size: 13px; background: white; }
        .student-id { font-size: 18px; font-weight: bold; color: #667eea; }
        .student-name { font-weight: bold; font-size: 16px; }
        .branch-status-container { display: flex; flex-direction: column; gap: 8px; }

        .mobile-expandable-view { display: none; }
        @media (max-width: 767px) {
            .standard-table-view { display: none; }
            .mobile-expandable-view { display: block; }
            <?php if ($lang == 'ur'): ?>
            .info-label, .info-value { font-size: 13px; }
            .student-name-card { font-size: 15px; }
            <?php endif; ?>
        }

        .expandable-row { border-radius: 12px; margin-bottom: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); overflow: hidden; transition: all 0.3s ease; border: 1px solid #c0c0c0; }
        .expandable-row:nth-child(odd) { background-color: #eef0f4; }
        .expandable-row:nth-child(even) { background-color: #cdd3dc; }
        .expandable-row:nth-child(odd) .collapsed-info { background-color: #fefefe; }
        .expandable-row:nth-child(even) .collapsed-info { background-color: #f0f2f4; }
        .collapsed-info { display: flex; justify-content: space-between; align-items: center; padding: 14px 16px; cursor: pointer; transition: background 0.2s ease; }
        .collapsed-info:active { background: #8a9bb8 !important; }
        .student-main-info { flex: 1; }
        .student-name-row { display: flex; align-items: baseline; flex-wrap: wrap; gap: 8px; margin-bottom: 6px; }
        .student-name-card { font-size: 16px; font-weight: 700; color: #1a2a3a; }
        .student-id-card { font-size: 12px; color: #1a4a8a; font-weight: 500; background: rgba(255,255,255,0.5); padding: 2px 8px; border-radius: 20px; }
        .student-class-card { font-size: 13px; color: #2c3e50; display: flex; align-items: center; gap: 6px; flex-wrap: wrap; }
        .expand-indicator { width: 32px; height: 32px; display: flex; align-items: center; justify-content: center; background: rgba(0,0,0,0.15); border-radius: 50%; transition: transform 0.3s ease; color: #2c3e50; }
        .expandable-row.expanded .expand-indicator { transform: rotate(180deg); background: #337ab7; color: white; }
        .expanded-content { display: none; padding: 0 16px 16px 16px; background: #e8edf5; border-top: 1px solid #b0b8c8; }
        .expandable-row.expanded .expanded-content { display: block; animation: fadeIn 0.3s ease; }
        @keyframes fadeIn { from { opacity: 0; transform: translateY(-10px); } to { opacity: 1; transform: translateY(0); } }
        .info-section { margin-top: 12px; }
        .info-section-title { font-size: 12px; font-weight: 600; color: #1a4a7a; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 10px; padding-bottom: 5px; border-bottom: 2px solid #b0bcc8; }
        .info-row { display: flex; justify-content: space-between; align-items: flex-start; padding: 8px 0; border-bottom: 1px solid #d0d8e4; }
        .info-row:last-child { border-bottom: none; }
        .info-label { font-size: 12px; font-weight: 600; color: #2c3e50; width: 40%; }
        .info-value { font-size: 13px; color: #1a2a3a; width: 60%; word-break: break-word; }
        .expanded-actions { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 15px; padding-top: 10px; }

        <?php if ($lang == 'ur'): ?>
        .expand-indicator { margin-left: 0; margin-right: auto; }
        .info-row { flex-direction: row; }
        .info-label { text-align: right; width: 40%; }
        .info-value { text-align: left; width: 60%; }
        .student-name-row { justify-content: flex-start; }
        <?php endif; ?>

        .loading-trigger { text-align: center; padding: 20px; margin-top: 10px; }
        .loader { border: 3px solid #f3f3f3; border-radius: 50%; border-top: 3px solid #3498db; width: 30px; height: 30px; animation: spin 1s linear infinite; display: inline-block; }
        @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
        .loading-message, .no-more-message { text-align: center; padding: 15px; color: #6c757d; background: #f8f9fa; border-radius: 5px; margin-top: 10px; }
        .alert { font-size: 14px !important; padding: 12px 18px !important; }
        .form-control { font-size: 14px !important; padding: 8px 12px !important; height: auto !important; }
        <?php if ($lang == 'ur'): ?>
        .form-control, input, select, textarea { text-align: right; font-size: 14px !important; }
        select.form-control option { text-align: right; }
        @media (max-width: 767px) {
            .form-group label { font-size: 13px !important; margin-bottom: 6px; }
            .filter-row .col-xs-12 { margin-bottom: 10px; }
        }
        <?php endif; ?>
        .form-group label { font-size: 14px; font-weight: 600; margin-bottom: 8px; }

        @media print {
            .btn, .navbar, .language-switcher, .search-box, .results-info,
            .loading-trigger, .mobile-expandable-view, .add-student-btn,
            .btn-print, .panel-heading .pull-right, .registration-header { display: none !important; }
            .standard-table-view { display: block !important; }
        }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script>
    var lang = <?php echo json_encode($js_translations, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP); ?>;
    var currentLang = '<?php echo $lang; ?>';
    var currentOffset = <?php echo $limit; ?>;
    var hasMore = <?php echo $has_more ? 'true' : 'false'; ?>;
    var isLoading = false;
    var currentParams = {
        search: '<?php echo addslashes($search); ?>',
        class_filter: '<?php echo $class_filter; ?>',
        village_filter: '<?php echo $village_filter; ?>',
        branch_filter: '<?php echo $branch_filter; ?>',
        status_filter: '<?php echo $status_filter; ?>',
        lang: currentLang
    };

    $(document).ready(function() {
        setTimeout(function() { $('.alert').fadeOut('slow'); }, 5000);
        $('input[name="search"]').focus();
        $('#class_filter, #village_filter, #branch_filter, #status_filter').change(function() { resetAndSubmitFilter(); });
        $('#filterForm').on('submit', function(e) { e.preventDefault(); resetAndSubmitFilter(); });
        $('.btn-warning').on('click', function(e) {
            if ($(this).hasClass('reset-btn')) {
                e.preventDefault();
                window.location.href = 'student_list.php<?php echo $lang != 'en' ? '?lang=' . $lang : ''; ?>';
            }
        });

        $(document).on('click', '.collapsed-info', function(e) {
            if ($(e.target).closest('.btn-action').length) return;
            $(this).closest('.expandable-row').toggleClass('expanded');
        });

        $(document).on('click', '.withdrawal-btn', function(e) {
            e.preventDefault(); e.stopPropagation();
            var studentId = $(this).data('student-id');
            if (confirm(lang.withdrawal_confirm)) {
                var form = $('<form method="POST" action=""></form>');
                form.append('<input type="hidden" name="withdrawal" value="1">');
                form.append('<input type="hidden" name="student_id" value="' + studentId + '">');
                form.append('<input type="hidden" name="lang" value="' + currentLang + '">');
                $('body').append(form);
                form.submit();
            }
        });

        $(document).on('click', '.toggle-type-btn', function(e) {
            e.preventDefault(); e.stopPropagation();
            var studentId = $(this).data('student-id');
            if (confirm(lang.toggle_confirm)) {
                var queryParams = $.param(currentParams);
                window.location.href = window.location.pathname + '?toggle_type=' + studentId + (queryParams ? '&' + queryParams : '');
            }
        });

        $(window).scroll(function() {
            if (isLoading || !hasMore) return;
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 200) { loadMoreStudents(); }
        });

        function loadMoreStudents() {
            if (isLoading || !hasMore) return;
            isLoading = true;
            if ($('.loading-trigger').length === 0) {
                $('.mobile-expandable-view').after('<div class="loading-trigger"><div class="loader"></div><div class="loading-message">' + lang.loading_more + '</div></div>');
            } else { $('.loading-trigger').show(); }
            var params = $.extend({}, currentParams);
            params.ajax_load = '1';
            params.offset = currentOffset;
            $.ajax({
                url: window.location.pathname, type: 'GET', data: params, dataType: 'json',
                success: function(response) {
                    if (response.success && response.students.length > 0) {
                        var container = $('.mobile-expandable-view');
                        $.each(response.students, function(index, student) {
                            var rowHtml = `
                                <div class="expandable-row" data-student-id="${student.id}">
                                    <div class="collapsed-info">
                                        <div class="student-main-info">
                                            <div class="student-name-row">
                                                <span class="student-name-card">${escapeHtml(student.name)}</span>
                                                <span class="student-id-card">ID: ${student.id}</span>
                                            </div>
                                            <div class="student-class-card">
                                                <span class="glyphicon glyphicon-education"></span>
                                                <span>${escapeHtml(student.class_title)}</span>
                                            </div>
                                        </div>
                                        <div class="expand-indicator"><span class="glyphicon glyphicon-chevron-down"></span></div>
                                    </div>
                                    <div class="expanded-content">
                                        <div class="info-section">
                                            <div class="info-section-title"><span class="glyphicon glyphicon-user"></span> <?php echo addslashes($translations[$lang]['student_info']); ?></div>
                                            <div class="info-row"><span class="info-label"><?php echo addslashes($translations[$lang]['father_name_label']); ?></span><span class="info-value">${escapeHtml(student.father_name)}</span></div>
                                            <div class="info-row"><span class="info-label"><?php echo addslashes($translations[$lang]['mobile_label']); ?></span><span class="info-value">${escapeHtml(student.mobile)}</span></div>
                                            <div class="info-row"><span class="info-label"><?php echo addslashes($translations[$lang]['reg_no_label']); ?></span><span class="info-value">${escapeHtml(student.reg_no)}</span></div>
                                            <div class="info-row"><span class="info-label"><?php echo addslashes($translations[$lang]['session_label']); ?></span><span class="info-value">${escapeHtml(student.session_title)}</span></div>
                                        </div>
                                        <div class="info-section">
                                            <div class="info-section-title"><span class="glyphicon glyphicon-earphone"></span> <?php echo addslashes($translations[$lang]['guardian_info']); ?></div>
                                            <div class="info-row"><span class="info-label"><?php echo addslashes($translations[$lang]['guardian_mobile_label']); ?></span><span class="info-value">${escapeHtml(student.guardian_mobile)}</span></div>
                                            <div class="info-row"><span class="info-label"><?php echo addslashes($translations[$lang]['guardian_cnic_label']); ?></span><span class="info-value">${escapeHtml(student.guardian_cnic)}</span></div>
                                        </div>
                                        <div class="info-section">
                                            <div class="info-section-title"><span class="glyphicon glyphicon-briefcase"></span> <?php echo addslashes($translations[$lang]['branch']); ?> & <?php echo addslashes($translations[$lang]['status']); ?></div>
                                            <div class="info-row"><span class="info-label"><?php echo addslashes($translations[$lang]['branch']); ?></span><span class="info-value">${escapeHtml(student.branch_name)}</span></div>
                                            <div class="info-row"><span class="info-label"><?php echo addslashes($translations[$lang]['status']); ?></span><span class="info-value"><span class="status-badge ${student.status_class}">${student.status_text}</span> <span class="type-badge ${student.type_class}" style="margin-left:8px;">${student.type_text}</span></span></div>
                                            <div class="info-row"><span class="info-label"><?php echo addslashes($translations[$lang]['village_council']); ?></span><span class="info-value">${escapeHtml(student.village_council_title)}</span></div>
                                        </div>
                                        <div class="expanded-actions">
                                            <a href="student_registration.php?edit=${student.id}${currentLang != 'en' ? '&lang=' + currentLang : ''}" class="btn btn-warning btn-action"><span class="glyphicon glyphicon-edit"></span> <?php echo addslashes($translations[$lang]['edit']); ?></a>
                                            <a href="student_registration_print.php?id=${student.id}${currentLang != 'en' ? '&lang=' + currentLang : ''}" class="btn btn-info btn-action" target="_blank"><span class="glyphicon glyphicon-print"></span> <?php echo addslashes($translations[$lang]['print_registration_form']); ?></a>
                                            <a href="student_fee_assignment.php?id=${student.id}${currentLang != 'en' ? '&lang=' + currentLang : ''}" class="btn btn-success btn-action"><span class="glyphicon glyphicon-usd"></span> <?php echo addslashes($translations[$lang]['collect_fee']); ?></a>
                                            <button type="button" class="btn btn-danger btn-action withdrawal-btn" data-student-id="${student.id}"><span class="glyphicon glyphicon-remove-circle"></span> <?php echo addslashes($translations[$lang]['withdrawal']); ?></button>
                                            <button type="button" class="btn btn-primary btn-action toggle-type-btn" data-student-id="${student.id}"><span class="glyphicon glyphicon-transfer"></span> <?php echo addslashes($translations[$lang]['toggle_type']); ?></button>
                                        </div>
                                    </div>
                                </div>`;
                            container.append(rowHtml);
                        });
                        currentOffset = response.offset;
                        hasMore = response.has_more;
                        $('.loading-trigger').remove();
                        if (!hasMore) { $('.mobile-expandable-view').after('<div class="no-more-message">' + lang.no_more_students + '</div>'); }
                    } else {
                        hasMore = false;
                        $('.loading-trigger').remove();
                        if ($('.no-more-message').length === 0) { $('.mobile-expandable-view').after('<div class="no-more-message">' + lang.no_more_students + '</div>'); }
                    }
                    isLoading = false;
                },
                error: function() { isLoading = false; $('.loading-trigger').remove(); }
            });
        }

        function resetAndSubmitFilter() {
            currentOffset = <?php echo $limit; ?>;
            hasMore = true; isLoading = false;
            $('.loading-trigger').remove(); $('.no-more-message').remove();
            currentParams = {
                search: $('input[name="search"]').val(),
                class_filter: $('#class_filter').val(),
                village_filter: $('#village_filter').val(),
                branch_filter: $('#branch_filter').val(),
                status_filter: $('#status_filter').val(),
                lang: currentLang
            };
            $('#filterForm').off('submit').submit();
        }

        function escapeHtml(text) {
            if (!text) return '';
            return $('<div>').text(text).html();
        }
    });
    </script>
</head>
<body>

<?php require_once('navbar.php'); ?>

<div class="container" style="margin-top: 20px;">
    <div class="row">
        <div class="col-md-12">

            <div class="registration-header">
                <a href="student_registration.php<?php echo $lang != 'en' ? '?lang=' . $lang : ''; ?>" class="btn btn-success student-list-btn">
                    <span class="glyphicon glyphicon-plus"></span>
                    <?php echo $translations[$lang]['add_new_student']; ?>
                </a>
                <div class="language-switcher">
                    <?php
                    $current_query = $_GET;
                    $current_query['lang'] = 'en';
                    $en_url = $_SERVER['PHP_SELF'] . '?' . http_build_query($current_query);
                    $current_query['lang'] = 'ur';
                    $ur_url = $_SERVER['PHP_SELF'] . '?' . http_build_query($current_query);
                    ?>
                    <a href="<?php echo htmlspecialchars($en_url); ?>" class="btn btn-default <?php echo ($lang == 'en') ? 'active' : ''; ?>">
                        <span class="glyphicon glyphicon-globe"></span> English
                    </a>
                    <a href="<?php echo htmlspecialchars($ur_url); ?>" class="btn btn-default <?php echo ($lang == 'ur') ? 'active' : ''; ?>">
                        <span class="glyphicon glyphicon-globe"></span> اردو
                    </a>
                </div>
            </div>

            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-list"></span>
                        <?php echo $translations[$lang]['list_title']; ?>
                        <span class="pull-right">
                            <a href="print_student_list.php?<?php echo $print_query_string; ?>" class="btn btn-print btn-xs text-white" target="_blank" title="<?php echo $translations[$lang]['print_filtered_list']; ?>">
                                <span class="glyphicon glyphicon-print"></span>
                                <?php echo $translations[$lang]['print_list']; ?>
                                <?php if ($total_students > 0): ?><span class="badge"><?php echo $total_students; ?></span><?php endif; ?>
                            </a>
                        </span>
                    </h3>
                </div>
                <div class="panel-body">

                    <div class="search-box">
                        <form method="GET" action="" id="filterForm">
                            <div class="form-group">
                                <label><span class="glyphicon glyphicon-search"></span> <?php echo $translations[$lang]['search_placeholder']; ?></label>
                                <div class="search-input-wrapper">
                                    <input type="text" class="form-control" name="search" placeholder="<?php echo $translations[$lang]['search_placeholder']; ?>" value="<?php echo htmlspecialchars($search); ?>">
                                    <span class="search-icon"><span class="glyphicon glyphicon-search"></span></span>
                                </div>
                            </div>
                            <div class="row filter-row">
                                <div class="col-xs-12 col-sm-6 col-md-3">
                                    <div class="form-group">
                                        <label><?php echo $translations[$lang]['filter_by_class']; ?></label>
                                        <select class="form-control" name="class_filter" id="class_filter">
                                            <option value="0"><?php echo $translations[$lang]['all_classes']; ?></option>
                                            <?php foreach ($classes as $id => $name): ?>
                                            <option value="<?php echo $id; ?>" <?php echo ($class_filter == $id) ? 'selected' : ''; ?>><?php echo htmlspecialchars($name); ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-3">
                                    <div class="form-group">
                                        <label><?php echo $translations[$lang]['filter_by_village']; ?></label>
                                        <select class="form-control" name="village_filter" id="village_filter">
                                            <option value="0"><?php echo $translations[$lang]['all_villages']; ?></option>
                                            <?php foreach ($village_councils as $id => $name): ?>
                                            <option value="<?php echo $id; ?>" <?php echo ($village_filter == $id) ? 'selected' : ''; ?>><?php echo htmlspecialchars($name); ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-3">
                                    <div class="form-group">
                                        <label><?php echo $translations[$lang]['filter_by_branch']; ?></label>
                                        <select class="form-control" name="branch_filter" id="branch_filter">
                                            <option value="0"><?php echo $translations[$lang]['all_branches']; ?></option>
                                            <?php foreach ($branches as $id => $name): ?>
                                            <option value="<?php echo $id; ?>" <?php echo ($branch_filter == $id) ? 'selected' : ''; ?>><?php echo htmlspecialchars($name); ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-3">
                                    <div class="form-group">
                                        <label><?php echo $translations[$lang]['filter_by_status']; ?></label>
                                        <select class="form-control" name="status_filter" id="status_filter">
                                            <option value="0" <?php echo ($status_filter == '0') ? 'selected' : ''; ?>><?php echo $translations[$lang]['active_students']; ?></option>
                                            <option value="1" <?php echo ($status_filter == '1') ? 'selected' : ''; ?>><?php echo $translations[$lang]['status_leave']; ?></option>
                                            <option value="2" <?php echo ($status_filter == '2') ? 'selected' : ''; ?>><?php echo $translations[$lang]['status_struck_off']; ?></option>
                                            <option value="all" <?php echo ($status_filter == 'all') ? 'selected' : ''; ?>><?php echo $translations[$lang]['all_status']; ?></option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="text-right">
                                <?php if ($search || $class_filter > 0 || $village_filter > 0 || $branch_filter > 0 || $status_filter != '0'): ?>
                                <a href="student_list.php<?php echo $lang != 'en' ? '?lang=' . $lang : ''; ?>" class="btn btn-warning reset-btn">
                                    <span class="glyphicon glyphicon-repeat"></span> <?php echo $translations[$lang]['reset_button']; ?>
                                </a>
                                <?php endif; ?>
                            </div>
                        </form>
                    </div>

                    <?php if ($search || $class_filter > 0 || $village_filter > 0 || $branch_filter > 0 || $status_filter != '0'): ?>
                    <div class="results-info">
                        <div><?php echo $translations[$lang]['total_students']; ?>: <strong><?php echo $total_students; ?></strong></div>
                        <div><a href="print_student_list.php?<?php echo $print_query_string; ?>" class="btn btn-sm btn-success" target="_blank"><?php echo $translations[$lang]['print_filtered_list']; ?></a></div>
                    </div>
                    <?php endif; ?>

                    <?php if (isset($_SESSION['message'])): ?>
                    <div class="alert alert-<?php echo $_SESSION['message_type']; ?> alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <?php echo $_SESSION['message']; unset($_SESSION['message'], $_SESSION['message_type']); ?>
                    </div>
                    <?php endif; ?>

                    <?php if ($result && $result->num_rows > 0): ?>

                    <!-- ===== DESKTOP TABLE VIEW ===== -->
                    <div class="standard-table-view">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th width="5%"><?php echo $translations[$lang]['sr_no']; ?></th>
                                        <th width="16%"><?php echo $translations[$lang]['student_id']; ?></th>
                                        <th width="16%"><?php echo $translations[$lang]['guardian_mobile_label']; ?></th>
                                        <th width="12%"><?php echo $translations[$lang]['class_or_course']; ?></th>
                                        <th width="12%"><?php echo $translations[$lang]['branch']; ?> &amp; <?php echo $translations[$lang]['status']; ?></th>
                                        <th width="10%"><?php echo $translations[$lang]['village_council']; ?></th>
                                        <th width="24%" class="text-center"><?php echo $translations[$lang]['actions']; ?></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    $count = 1;
                                    $result->data_seek(0);
                                    while ($row = $result->fetch_assoc()):
                                        $status_class = ($row['status'] == 1) ? 'status-leave' : (($row['status'] == 2) ? 'status-struck' : 'status-active');
                                        $status_text  = ($row['status'] == 1) ? $translations[$lang]['status_leave'] : (($row['status'] == 2) ? $translations[$lang]['status_struck_off'] : $translations[$lang]['status_active']);
                                        $student_type = isset($row['student_type']) ? $row['student_type'] : 'Regular';
                                        $type_class   = ($student_type == 'Regular') ? 'type-regular' : 'type-hostilized';
                                        $type_text    = ($student_type == 'Regular') ? $translations[$lang]['regular'] : $translations[$lang]['hostilized'];
                                        $branch_name  = htmlspecialchars($row['branch_name'] ?? 'N/A');
                                    ?>
                                    <tr>
                                        <td class="text-center"><?php echo $count++; ?></td>
                                        <td>
                                            <div class="student-id">ID: <?php echo $row['id']; ?></div>
                                            <strong class="student-name"><?php echo htmlspecialchars($row['name']); ?></strong><br>
                                            <small class="text-muted">
                                                <?php echo $translations[$lang]['father_name_label']; ?> <?php echo htmlspecialchars($row['father_name']); ?><br>
                                                <?php echo $translations[$lang]['mobile_label']; ?> <?php echo htmlspecialchars($row['mobile']); ?><br>
                                                <?php echo $translations[$lang]['reg_no_label']; ?> <?php echo htmlspecialchars($row['reg_no']); ?>
                                            </small>
                                        </td>
                                        <td>
                                            <strong><?php echo htmlspecialchars($row['guardian_name']); ?></strong><br>
                                            <small class="text-muted">
                                                <?php echo $translations[$lang]['guardian_mobile_label']; ?> <?php echo htmlspecialchars($row['guardian_mobile']); ?><br>
                                                <?php echo $translations[$lang]['guardian_cnic_label']; ?> <?php echo htmlspecialchars($row['guardian_cnic']); ?>
                                            </small>
                                        </td>
                                        <td>
                                            <strong><?php echo $translations[$lang]['class_or_course']; ?></strong><br>
                                            <?php echo htmlspecialchars($row['class_title'] ?? 'Not Assigned'); ?><br>
                                            <small class="text-muted">
                                                <?php echo $translations[$lang]['session_label']; ?> <?php echo htmlspecialchars($row['session_title'] ?? 'Not Assigned'); ?>
                                            </small>
                                        </td>
                                        <td>
                                            <div class="branch-status-container">
                                                <span class="branch-item"><?php echo $branch_name; ?></span>
                                                <span class="status-badge <?php echo $status_class; ?>"><?php echo $status_text; ?></span>
                                                <span class="type-badge <?php echo $type_class; ?>"><?php echo $type_text; ?></span>
                                            </div>
                                        </td>
                                        <td><?php echo htmlspecialchars($row['village_council_title'] ?? 'N/A'); ?></td>
                                        <td class="text-center">
                                            <div class="btn-group-actions">
                                                <!-- ══════════════════════════════════════════════
                                                     FIX: href uses student_registration.php?edit=ID
                                                     All </td> and </tr> are now correct HTML tags
                                                ══════════════════════════════════════════════ -->
                                                <a href="student_registration.php?edit=<?php echo (int)$row['id']; ?><?php echo $lang != 'en' ? '&lang=' . $lang : ''; ?>" class="btn btn-warning btn-action">
                                                    <span class="glyphicon glyphicon-edit"></span> <?php echo $translations[$lang]['edit']; ?>
                                                </a>
                                                <a href="student_registration_print.php?id=<?php echo (int)$row['id']; ?><?php echo $lang != 'en' ? '&lang=' . $lang : ''; ?>" class="btn btn-info btn-action" target="_blank">
                                                    <span class="glyphicon glyphicon-print"></span> <?php echo $translations[$lang]['print_registration_form']; ?>
                                                </a>
                                                <a href="student_fee_assignment.php?id=<?php echo (int)$row['id']; ?><?php echo $lang != 'en' ? '&lang=' . $lang : ''; ?>" class="btn btn-success btn-action">
                                                    <span class="glyphicon glyphicon-usd"></span> <?php echo $translations[$lang]['collect_fee']; ?>
                                                </a>
                                                <button type="button" class="btn btn-danger btn-action withdrawal-btn" data-student-id="<?php echo (int)$row['id']; ?>">
                                                    <span class="glyphicon glyphicon-remove-circle"></span> <?php echo $translations[$lang]['withdrawal']; ?>
                                                </button>
                                                <button type="button" class="btn btn-primary btn-action toggle-type-btn" data-student-id="<?php echo (int)$row['id']; ?>">
                                                    <span class="glyphicon glyphicon-transfer"></span> <?php echo $translations[$lang]['toggle_type']; ?>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                    <?php endwhile; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <!-- ===== MOBILE EXPANDABLE VIEW ===== -->
                    <div class="mobile-expandable-view">
                        <?php
                        $result->data_seek(0);
                        while ($row = $result->fetch_assoc()):
                            $status_class = ($row['status'] == 1) ? 'status-leave' : (($row['status'] == 2) ? 'status-struck' : 'status-active');
                            $status_text  = ($row['status'] == 1) ? $translations[$lang]['status_leave'] : (($row['status'] == 2) ? $translations[$lang]['status_struck_off'] : $translations[$lang]['status_active']);
                            $student_type = isset($row['student_type']) ? $row['student_type'] : 'Regular';
                            $type_class   = ($student_type == 'Regular') ? 'type-regular' : 'type-hostilized';
                            $type_text    = ($student_type == 'Regular') ? $translations[$lang]['regular'] : $translations[$lang]['hostilized'];
                            $branch_name  = htmlspecialchars($row['branch_name'] ?? 'N/A');
                        ?>
                        <div class="expandable-row" data-student-id="<?php echo $row['id']; ?>">
                            <div class="collapsed-info">
                                <div class="student-main-info">
                                    <div class="student-name-row">
                                        <span class="student-name-card"><?php echo htmlspecialchars($row['name']); ?></span>
                                        <span class="student-id-card">ID: <?php echo $row['id']; ?></span>
                                    </div>
                                    <div class="student-class-card">
                                        <span class="glyphicon glyphicon-education"></span>
                                        <span><?php echo htmlspecialchars($row['class_title'] ?? 'Not Assigned'); ?></span>
                                    </div>
                                </div>
                                <div class="expand-indicator"><span class="glyphicon glyphicon-chevron-down"></span></div>
                            </div>
                            <div class="expanded-content">
                                <div class="info-section">
                                    <div class="info-section-title"><?php echo $translations[$lang]['student_info']; ?></div>
                                    <div class="info-row"><span class="info-label"><?php echo $translations[$lang]['father_name_label']; ?></span><span class="info-value"><?php echo htmlspecialchars($row['father_name']); ?></span></div>
                                    <div class="info-row"><span class="info-label"><?php echo $translations[$lang]['mobile_label']; ?></span><span class="info-value"><?php echo htmlspecialchars($row['mobile']); ?></span></div>
                                    <div class="info-row"><span class="info-label"><?php echo $translations[$lang]['reg_no_label']; ?></span><span class="info-value"><?php echo htmlspecialchars($row['reg_no']); ?></span></div>
                                    <div class="info-row"><span class="info-label"><?php echo $translations[$lang]['session_label']; ?></span><span class="info-value"><?php echo htmlspecialchars($row['session_title'] ?? 'Not Assigned'); ?></span></div>
                                </div>
                                <div class="info-section">
                                    <div class="info-section-title"><?php echo $translations[$lang]['guardian_info']; ?></div>
                                    <div class="info-row"><span class="info-label"><?php echo $translations[$lang]['guardian_mobile_label']; ?></span><span class="info-value"><?php echo htmlspecialchars($row['guardian_mobile']); ?></span></div>
                                    <div class="info-row"><span class="info-label"><?php echo $translations[$lang]['guardian_cnic_label']; ?></span><span class="info-value"><?php echo htmlspecialchars($row['guardian_cnic']); ?></span></div>
                                </div>
                                <div class="info-section">
                                    <div class="info-section-title"><?php echo $translations[$lang]['branch']; ?> &amp; <?php echo $translations[$lang]['status']; ?></div>
                                    <div class="info-row"><span class="info-label"><?php echo $translations[$lang]['branch']; ?></span><span class="info-value"><?php echo $branch_name; ?></span></div>
                                    <div class="info-row"><span class="info-label"><?php echo $translations[$lang]['status']; ?></span><span class="info-value"><span class="status-badge <?php echo $status_class; ?>"><?php echo $status_text; ?></span> <span class="type-badge <?php echo $type_class; ?>"><?php echo $type_text; ?></span></span></div>
                                    <div class="info-row"><span class="info-label"><?php echo $translations[$lang]['village_council']; ?></span><span class="info-value"><?php echo htmlspecialchars($row['village_council_title'] ?? 'N/A'); ?></span></div>
                                </div>
                                <div class="expanded-actions">
                                    <a href="student_registration.php?edit=<?php echo (int)$row['id']; ?><?php echo $lang != 'en' ? '&lang=' . $lang : ''; ?>" class="btn btn-warning btn-action">
                                        <span class="glyphicon glyphicon-edit"></span> <?php echo $translations[$lang]['edit']; ?>
                                    </a>
                                    <a href="student_registration_print.php?id=<?php echo (int)$row['id']; ?><?php echo $lang != 'en' ? '&lang=' . $lang : ''; ?>" class="btn btn-info btn-action" target="_blank">
                                        <span class="glyphicon glyphicon-print"></span> <?php echo $translations[$lang]['print_registration_form']; ?>
                                    </a>
                                    <a href="student_fee_assignment.php?id=<?php echo (int)$row['id']; ?><?php echo $lang != 'en' ? '&lang=' . $lang : ''; ?>" class="btn btn-success btn-action">
                                        <span class="glyphicon glyphicon-usd"></span> <?php echo $translations[$lang]['collect_fee']; ?>
                                    </a>
                                    <button type="button" class="btn btn-danger btn-action withdrawal-btn" data-student-id="<?php echo (int)$row['id']; ?>">
                                        <span class="glyphicon glyphicon-remove-circle"></span> <?php echo $translations[$lang]['withdrawal']; ?>
                                    </button>
                                    <button type="button" class="btn btn-primary btn-action toggle-type-btn" data-student-id="<?php echo (int)$row['id']; ?>">
                                        <span class="glyphicon glyphicon-transfer"></span> <?php echo $translations[$lang]['toggle_type']; ?>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <?php endwhile; ?>
                    </div>

                    <?php if ($has_more): ?>
                    <div class="loading-trigger" style="display: none;"></div>
                    <?php endif; ?>

                    <?php else: ?>
                    <div class="alert alert-info text-center">
                        <h4><?php echo $translations[$lang]['no_records']; ?></h4>
                    </div>
                    <?php endif; ?>

                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>
<?php $conn->close(); ?>